#!/usr/bin/env python3
"""
Inject rendered diagram images into markdown by chapter headings.

Input:
- markdown content
- diagram manifest generated by render_diagrams.py

Output:
- markdown with image lines injected in chapter 1/2/3 sections
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple


CHAPTER_HEADING_PATTERNS = {
    "chapter1": r"^##\s*一[、\.]\s*需求理解",
    "chapter2": r"^##\s*二[、\.]\s*实施策略",
    "chapter3": r"^##\s*三[、\.]\s*运营方案",
}


def _load_manifest(path: Path) -> List[Dict]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    items = payload.get("items", [])
    if not isinstance(items, list):
        raise ValueError("Invalid manifest format: items must be a list.")
    return items


def _pick_diagrams(items: List[Dict]) -> Dict[str, Dict]:
    picked: Dict[str, Dict] = {}
    for item in items:
        if item.get("status") != "ok":
            continue
        chapter = str(item.get("chapter", "")).strip()
        if chapter not in CHAPTER_HEADING_PATTERNS:
            continue
        if chapter not in picked:
            picked[chapter] = item
    return picked


def _find_heading_line(lines: List[str], pattern: str) -> int:
    rx = re.compile(pattern)
    for i, line in enumerate(lines):
        if rx.search(line.strip()):
            return i
    return -1


def _build_image_block(item: Dict, md_dir: Path) -> List[str]:
    title = str(item.get("title", "")).strip() or "逻辑图"
    image_path = Path(str(item.get("image_path", "")).strip())
    if image_path.is_absolute():
        rel = image_path
        try:
            rel = image_path.relative_to(md_dir)
        except Exception:
            rel = image_path
    else:
        rel = image_path

    rel_str = str(rel).replace("\\", "/")
    return [f"![{title}]({rel_str})", ""]


def inject(markdown: str, chapter_images: Dict[str, Dict], md_path: Path) -> str:
    lines = markdown.splitlines()
    inserts: List[Tuple[int, List[str]]] = []

    for chapter, pattern in CHAPTER_HEADING_PATTERNS.items():
        item = chapter_images.get(chapter)
        if not item:
            continue
        idx = _find_heading_line(lines, pattern)
        if idx == -1:
            continue
        block = _build_image_block(item, md_path.parent)
        # Insert after chapter heading, leaving one line gap.
        insert_at = idx + 1
        inserts.append((insert_at, block))

    # Apply inserts from bottom to top to keep indices stable.
    for insert_at, block in sorted(inserts, key=lambda x: x[0], reverse=True):
        lines[insert_at:insert_at] = block

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Inject rendered diagrams into markdown chapters.")
    parser.add_argument("--input-md", required=True, help="Input markdown path")
    parser.add_argument("--manifest", required=True, help="Diagram manifest JSON path")
    parser.add_argument("--output-md", required=True, help="Output markdown path")
    args = parser.parse_args()

    in_md = Path(args.input_md)
    manifest = Path(args.manifest)
    out_md = Path(args.output_md)

    if not in_md.exists():
        print(f"Input markdown not found: {in_md}")
        return 1
    if not manifest.exists():
        print(f"Manifest not found: {manifest}")
        return 1

    try:
        items = _load_manifest(manifest)
        chapter_images = _pick_diagrams(items)
        markdown = in_md.read_text(encoding="utf-8")
        new_md = inject(markdown, chapter_images, out_md)
        out_md.write_text(new_md, encoding="utf-8")
        print(f"Injected diagrams for chapters: {', '.join(sorted(chapter_images.keys())) or 'none'}")
        print(f"Output markdown: {out_md}")
        return 0
    except Exception as e:
        print(f"Inject failed: {e}")
        return 2


if __name__ == "__main__":
    sys.exit(main())
